command:
- python
- -u
- training.py
- --num_timesteps
- '2000000'
- --batch_size
- '4096'
- --log_wandb
- --exp_name
- sweep_all_2D
- --use_ln
- '1'
- --use_bias
- ${use_bias}
- --use_ortho_P
- ${use_ortho_P}
- --fits_in_vram
- --group_name
- rep_sweep
- --repr_fn
- ${repr_fn}
- --repr_dim
- ${repr_dim}
- --h_dim
- '256'
- --num_layers
- ${num_layers}
- --seed
- ${seed}
- --contrastive_loss_fn
- ${contrastive_loss_fn}
- --data_folder_to_analyze
- ${data_folder_to_analyze}
- --datasets_to_analyze
- ${datasets_to_analyze}
- --energy_fn
- ${energy_fn}
- --precision
- ${precision}
- --lr
- ${lr}
- --patience
- ${patience}
- --linear_network
- ${linear_network}
- --frac_of_data
- ${frac_of_data}
- --render_load
method: grid
parameters:
  contrastive_loss_fn:
    values:
    - forward_backward
  data_folder_to_analyze:
    values:
    - /n/fs/rl-cj7280/epr_estimator/datasets/figures_dataset_dump/nbeads_N=32,64_mode=alternate_figures_sweep
  energy_fn:
    values:
    - dot
  frac_of_data:
    values:
    - 1.0
  linear_network:
    values:
    - true
    - false
  lr:
    values:
    - 3.0e-05
  num_layers:
    values:
    - 2
  patience:
    values:
    - 7
  precision:
    values:
    - highest
  repr_dim:
    values:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
  repr_fn:
    values:
    - linear_local_subspaces
  seed:
    values:
    - 0
  use_bias:
    values:
    - true
  use_ortho_P:
    values:
    - false
program: training.py
