directory: "/n/fs/rl-cj7280/epr_for_release/datasets/"
grid_size:
  - 64
dt:
  - 0.001
num_steps:
  - 10000000
save_every:
  - 100
alpha: 
  - -0.8
beta:
  - 0.0
  - 0.4
  - 0.8
  - 1.2
  - 1.6
  - 2.0
batch_size:
  - 100000
seed:
  - 0
  - 1
  - 2
  - 3
  - 4
with_warmup:
  - False
eps:
  - 0.01
save_amp:
  - False