directory: "/n/fs/rl-cj7280/epr_for_release/datasets/"
U0:
  - 1.0
kappa:
  - 0.4
  - 0.6
  - 0.8
  - 1.0
  - 1.2
  - 1.4
  - 1.6
  - 1.8
D: 
  - 1.0
dt:
  - 0.001
save_every:
  - 10
max_episode_steps:
  - 1000000
num_episodes:
  - 10
seed:
  - 0
  - 1
  - 2
  - 3
  - 4
save_sin_cos: 
  - False
batch_size:
  - 2048